apiVersion: v2
name: captcha
description: A Helm chart for MOSIP Captcha Service
type: application
version: 0.1.0-beta.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - captcha
maintainers:
  - email: info@mosip.io
    name: MOSIP
